version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql
    environment:
      - PYTHONPATH=/app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rag_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
volumes:
  mysql-data: